---
kind: pipeline
name: test

steps:

# Build Dependencies & Structure

- name: build-structure
  image: alpine:3.8
  commands:
  - apk add make
  - make folder-structure layout-images env-file-blank
    
- name: build-composer
  image: composer
  commands:
  - cd src/
  - composer install --ignore-platform-reqs --no-scripts
    
- name: build-npm
  image: node:8
  commands:
  - cd src/
  - npm install && node_modules/.bin/gulp --production

# Build Docker Image

- name: build-image
  image: plugins/docker
  settings:
    repo: lanopsdev/manager
    tags: 
    - latest
    dry_run: true

# Tests

- name: test-phpunit
  image: lanopsdev/manager:latest
  environment:
    APP_KEY:
      from_secret: TEST_APP_KEY
    DB_HOST: database
    DB_DATABASE: lan_manager
    DB_USERNAME: lan_manager
    DB_PASSWORD: password
    APP_DEBUG: true
    APP_ENV: testing
    APP_URL: localhost
  commands:
  - cd /web/html/
  - ls
  - php artisan migrate --force
  - php artisan db:seed --force
  - vendor/bin/phpunit

trigger:
  branch:
  - master
  - staging

services:
- name: database
  image: mysql:5.6
  environment:
    MYSQL_DATABASE: lan_manager
    MYSQL_USER: lan_manager
    MYSQL_PASSWORD: password
    MYSQL_RANDOM_ROOT_PASSWORD: true

---
kind: pipeline
name: build-untagged

steps:

# Notifacations - Start

- name: notify-discord-start
  image: plugins/webhook
  settings:
    urls:
      from_secret: DISCORD_WEBHOOK_URL
    template: |
      {
        "username": "Lan Manager Drone",
        "content": "__***{{uppercase build.branch }}***__ - \"${DRONE_COMMIT_MESSAGE}\" - Build Started.",
        "avatar_url": "https://cdn.worldvectorlogo.com/logos/drone.svg"
      }
  when:
    event:
    - push
    branch:
    - master
    - staging

# Build Dependencies & Structure

- name: build-structure
  image: alpine:3.8
  commands:
  - apk add make
  - make folder-structure layout-images env-file-blank
  when:
    event:
    - push
    
- name: build-composer
  image: composer
  commands:
  - cd src/
  - composer install --ignore-platform-reqs --no-scripts
  when:
    event:
    - push
    
- name: build-npm
  image: node:8
  commands:
  - cd src/
  - npm install && node_modules/.bin/gulp --production
  when:
    event:
    - push

# Build & Push Docker Image

- name: push-image-staging
  image: plugins/docker
  settings:
    repo: lanopsdev/manager
    tags: 
    - staging
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
  when:
    branch:
    - staging
    status:
    - success

- name: push-image-master
  image: plugins/docker
  settings:
    repo: lanopsdev/manager
    tags: 
    - latest
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
  when:
    branch:
    - master
    status:
    - success

# Notifcations - End

- name: notify-discord-test-success
  image: plugins/webhook
  settings:
    urls:
      from_secret: DISCORD_WEBHOOK_URL
    template: |
      {
        "username": "Lan Manager Drone",
        "content": "__***{{uppercase build.branch }}***__ - \"${DRONE_COMMIT_MESSAGE}\" - Commit: {{ build.commit }} Passed. GGWP!",
        "avatar_url": "https://cdn.worldvectorlogo.com/logos/drone.svg"
      }
  when:
    event:
    - push
    status:
    - success

- name: notify-discord-test-failure
  image: plugins/webhook
  settings:
    urls:
      from_secret: DISCORD_WEBHOOK_URL
    template: |
      {
        "username": "Lan Manager Drone",
        "content": "__***{{uppercase build.branch }}***__ - \"${DRONE_COMMIT_MESSAGE}\" - Commit: {{ build.commit }} Failed. Fix me please!",
        "avatar_url": "https://cdn.worldvectorlogo.com/logos/drone.svg"
      }
  when:
    event:
    - push
    status:
    - failure

- name: notify-discord-image-pushed-staging
  image: plugins/webhook
  settings:
    urls:
      from_secret: DISCORD_WEBHOOK_URL
    template: |
      {
        "username": "Lan Manager Drone",
        "content": "__***{{uppercase build.branch }}***__ - \"${DRONE_COMMIT_MESSAGE}\" - Commit: {{ build.commit }} - Image has been built and pushed to Docker Hub.",
        "avatar_url": "https://cdn.worldvectorlogo.com/logos/drone.svg"
      }
  when:
    branch:
    - staging
    status:
    - success

- name: notify-discord-image-pushed-master
  image: plugins/webhook
  settings:
    urls:
      from_secret: DISCORD_WEBHOOK_URL
    template: |
      {
        "username": "Lan Manager Drone",
        "content": "__***{{uppercase build.branch }}***__ - \"${DRONE_COMMIT_MESSAGE}\" - Commit: {{ build.commit }} - Image has been built and pushed to Docker Hub.",
        "avatar_url": "https://cdn.worldvectorlogo.com/logos/drone.svg"
      }
  when:
    event:
    - push
    branch:
    - master
    status:
    - success

trigger:
  status:
  - success
  event:
  - push
  branch:
  - master
  - staging

depends_on:
- test

services:
- name: database
  image: mysql:5.6
  environment:
    MYSQL_DATABASE: lan_manager
    MYSQL_USER: lan_manager
    MYSQL_PASSWORD: password
    MYSQL_RANDOM_ROOT_PASSWORD: true

---
kind: pipeline
name: build-tagged

steps:

# Notifacations - Start

- name: notify-discord-start-master-tagged
  image: plugins/webhook
  settings:
    urls:
      from_secret: DISCORD_WEBHOOK_URL
    template: |
      {
        "username": "Lan Manager Drone",
        "content": "__***{{uppercase build.branch }}***__ - \"${DRONE_COMMIT_MESSAGE}\" - **TAGGED** Docker Build Started.",
        "avatar_url": "https://cdn.worldvectorlogo.com/logos/drone.svg"
      }
  when:
    event:
    - tag

# Build Dependencies & Structure

- name: build-structure
  image: alpine:3.8
  commands:
  - apk add make
  - make folder-structure layout-images env-file-blank
  when:
    event:
    - tag
    
- name: build-composer
  image: composer
  commands:
  - cd src/
  - composer install --ignore-platform-reqs --no-scripts
  when:
    event:
    - tag
    
- name: build-npm
  image: node:8
  commands:
  - cd src/
  - npm install && node_modules/.bin/gulp --production
  when:
    event:
    - tag

# Build & Push Docker Image

- name: build-push-image-tagged
  image: plugins/docker
  settings:
    repo: lanopsdev/manager
    tags: 
    - ${DRONE_TAG}
    - latest
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
  when:
    event:
    - tag
    status:
    - success

# Notifcations - End

- name: notify-discord-image-pushed-master-failure
  image: plugins/webhook
  settings:
    urls:
      from_secret: DISCORD_WEBHOOK_URL
    template: |
      {
        "username": "Lan Manager Drone",
        "content": "__***{{uppercase build.branch }}***__ - \"${DRONE_COMMIT_MESSAGE}\" - Commit: {{ build.commit }} Failed. Fix me please!",
        "avatar_url": "https://cdn.worldvectorlogo.com/logos/drone.svg"
      }
  when:
    event:
    - tag
    status:
    - failure

- name: notify-discord-image-pushed-master-tagged
  image: plugins/webhook
  settings:
    urls:
      from_secret: DISCORD_WEBHOOK_URL
    template: |
      {
        "username": "Lan Manager Drone",
        "content": "__***{{uppercase build.branch }}***__ - \"${DRONE_COMMIT_MESSAGE}\" - Commit: {{ build.commit }} - Image has been built and pushed to Docker Hub.",
        "avatar_url": "https://cdn.worldvectorlogo.com/logos/drone.svg"
      }
  when:
    event:
    - tag
    status:
    - success

trigger:
  event:
  - tag

depends_on:
- test

services:
- name: database
  image: mysql:5.6
  environment:
    MYSQL_DATABASE: lan_manager
    MYSQL_USER: lan_manager
    MYSQL_PASSWORD: password
    MYSQL_RANDOM_ROOT_PASSWORD: true

---
kind: signature
hmac: a46f699db6441ebd681cb87f342ee6508c0552f0459ef76edf24cab73b2e6fdf

...
