---
kind: pipeline
name: default

steps:

# Notifacations - Start

- name: notify-discord-start-staging
  image: plugins/webhook
  settings:
    urls:
      from_secret: DISCORD_WEBHOOK_URL
    template: |
      {
        "username": "Lan Manager Drone",
        "content": "__***{{uppercase build.branch }}***__ - \"${DRONE_COMMIT_MESSAGE}\" - Docker Build Started.",
        "avatar_url": "https://cdn.worldvectorlogo.com/logos/drone.svg"
      }
  when:
    event:
    - push
    branch:
    - staging

- name: notify-discord-start-master-tagged
  image: plugins/webhook
  settings:
    urls:
      from_secret: DISCORD_WEBHOOK_URL
    template: |
      {
        "username": "Lan Manager Drone",
        "content": "__***{{uppercase build.branch }}***__ - \"${DRONE_COMMIT_MESSAGE}\" - **TAGGED** Docker Build Started.",
        "avatar_url": "https://cdn.worldvectorlogo.com/logos/drone.svg"
      }
  when:
    event:
    - push
    - tag
    branch:
    - master

# Build Dependencies & Structure

- name: build-structure
  image: alpine:3.8
  commands:
  - apk add make
  - make folder-structure layout-images env-file
  when:
    event:
    - push
    - pull_request
    
- name: build-composer
  image: composer
  commands:
  - cd src/
  - composer install --ignore-platform-reqs --no-scripts
  when:
    event:
    - push
    - pull_request
    
- name: build-npm
  image: node:8
  commands:
  - cd src/
  - npm install && node_modules/.bin/gulp --production
  when:
    event:
    - push
    - pull_request

# Build Docker Image

- name: build-image
  image: plugins/docker
  settings:
    repo: lanopsdev/manager
    tags: 
    - latest
    - staging
    dry_run: true
  when:
    event:
    - push
    - pull_request

- name: build-image-tagged
  image: plugins/docker
  settings:
    repo: lanopsdev/manager
    tags: 
    - ${DRONE_TAG}
    dry_run: true
  when:
    event:
    - tag
    branch:
    - master

# Tests

- name: test-phpunit
  image: lanopsdev/manager:latest
  environment:
    APP_KEY:
      from_secret: TEST_APP_KEY
  commands:
  - cd /web/html/
  - ls
  - php artisan migrate --force
  - php artisan db:seed --force
  - vendor/bin/phpunit
  when:
    event:
    - push
    - pull_request

# Push Docker Image

- name: push-image-staging
  image: plugins/docker
  settings:
    repo: lanopsdev/manager
    tags: 
    - staging
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
  when:
    event:
      exclude:
      - pull_request
    branch:
    - staging
    status:
    - success

- name: push-image-master
  image: plugins/docker
  settings:
    repo: lanopsdev/manager
    tags: 
    - ${DRONE_TAG}
    - latest
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
  when:
    event:
    - tag
    branch:
    - master
    status:
    - success

# Notifcations - End

- name: notify-discord-test-success
  image: plugins/webhook
  settings:
    urls:
      from_secret: DISCORD_WEBHOOK_URL
    template: |
      {
        "username": "Lan Manager Drone",
        "content": "__***{{uppercase build.branch }}***__ - \"${DRONE_COMMIT_MESSAGE}\" - Commit: {{ build.commit }} Passed. GGWP!",
        "avatar_url": "https://cdn.worldvectorlogo.com/logos/drone.svg"
      }
  when:
    event:
    - push
    - pull_request
    status:
    - success

- name: notify-discord-test-failure
  image: plugins/webhook
  settings:
    urls:
      from_secret: DISCORD_WEBHOOK_URL
    template: |
      {
        "username": "Lan Manager Drone",
        "content": "__***{{uppercase build.branch }}***__ - \"${DRONE_COMMIT_MESSAGE}\" - Commit: {{ build.commit }} Failed. Fix me please!",
        "avatar_url": "https://cdn.worldvectorlogo.com/logos/drone.svg"
      }
  when:
    event:
    - push
    - pull_request
    status:
    - failure

- name: notify-discord-image-pushed-staging
  image: plugins/webhook
  settings:
    urls:
      from_secret: DISCORD_WEBHOOK_URL
    template: |
      {
        "username": "Lan Manager Drone",
        "content": "__***{{uppercase build.branch }}***__ - \"${DRONE_COMMIT_MESSAGE}\" - Commit: {{ build.commit }} - Image has been built and pushed to Docker Hub.",
        "avatar_url": "https://cdn.worldvectorlogo.com/logos/drone.svg"
      }
  when:
    branch:
    - staging
    status:
    - success

- name: notify-discord-image-pushed-master-tagged
  image: plugins/webhook
  settings:
    urls:
      from_secret: DISCORD_WEBHOOK_URL
    template: |
      {
        "username": "Lan Manager Drone",
        "content": "__***{{uppercase build.branch }}***__ - \"${DRONE_COMMIT_MESSAGE}\" - Commit: {{ build.commit }} - Image has been built and pushed to Docker Hub.",
        "avatar_url": "https://cdn.worldvectorlogo.com/logos/drone.svg"
      }
  when:
    event:
    - tag
    branch:
    - master
    status:
    - success

trigger:
  branch:
  - master
  - staging

services:
- name: database
  image: mysql:5.6
  environment:
    MYSQL_DATABASE: lan_manager
    MYSQL_USER: lan_manager
    MYSQL_PASSWORD: password
    MYSQL_RANDOM_ROOT_PASSWORD: true
---
kind: signature
hmac: dd6fc58afc46642322402a7f279c6bcd1f0c15d24b161fa24fb5694fdc00d95d

...
